API_KEY = 'FHUDK77EPUPMJJBY'
ENDPOINT_SCHEMA_URL = 'https://psrc-22y2ny.us-west2.gcp.confluent.cloud'
API_SECRET_KEY = 'Cc0myt383V5EeDrqjvM1jA27MDN1yJQwSG+gKnjYbttybPlUKEcGFXujWJwhpo/Y'
BOOTSTRAP_SERVER = 'pkc-12576z.us-west2.gcp.confluent.cloud:9092'
SECURITY_PROTOCOL = 'SASL_SSL'
SSL_MECHANISM = 'PLAIN'
SCHEMA_REGISTRY_API_KEY = 'VB5JUASPHPAWEE2A'
SCHEMA_REGISTRY_API_SECRET = 'LHa78WL6tKe7E4/VolewNKpAsTwCXYYiaQXMyYoDgN2PgmE5zahJjb1mjkWKEDoj'


def config_values():
    return API_KEY, ENDPOINT_SCHEMA_URL, API_SECRET_KEY, BOOTSTRAP_SERVER, SECURITY_PROTOCOL, SSL_MECHANISM, SCHEMA_REGISTRY_API_KEY, SCHEMA_REGISTRY_API_SECRET
